package PO.user;
// Generated 2017-6-6 1:42:06 by Hibernate Tools 4.0.1.Final

/**
 * UserStockPool generated by hbm2java
 */
public class UserStockPool implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3654180816183071005L;
	private Integer id;
	private String username;
	private String stockcode;

	public UserStockPool() {
	}

	public UserStockPool(String username, String stockcode) {
		this.username = username;
		this.stockcode = stockcode;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getStockcode() {
		return this.stockcode;
	}

	public void setStockcode(String stockcode) {
		this.stockcode = stockcode;
	}

}
