package PO.user;
// Generated 2017-6-2 16:54:51 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * UserAccount generated by hbm2java
 */
public class UserAccount implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6197363525843231968L;
	private String username;
	//可交易金额
	private Double availablePrincipal;
	//已用于购买的金额
	private Double storagePrincipal;
	
	private Double profit;
	private Date signdate;
	
	private Integer consecutiveDaysNum;
	//仅用于计算profit ，不向上层展示
	private Double historyPrincipal;

	private Double todayProfit;
	private Double yesterdayPrincipal;
	
	public UserAccount() {
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Double getAvailablePrincipal() {
		return availablePrincipal;
	}

	public void setAvailablePrincipal(Double availablePrincipal) {
		this.availablePrincipal = availablePrincipal;
	}

	public Double getStoragePrincipal() {
		return storagePrincipal;
	}

	public void setStoragePrincipal(Double storagePrincipal) {
		this.storagePrincipal = storagePrincipal;
	}

	public Double getProfit() {
		return profit;
	}

	public void setProfit(Double profit) {
		this.profit = profit;
	}

	public Date getSigndate() {
		return signdate;
	}

	public void setSigndate(Date signdate) {
		this.signdate = signdate;
	}

	public Integer getConsecutiveDaysNum() {
		return consecutiveDaysNum;
	}

	public void setConsecutiveDaysNum(Integer consecutiveDaysNum) {
		this.consecutiveDaysNum = consecutiveDaysNum;
	}

	public Double getHistoryPrincipal() {
		return historyPrincipal;
	}

	public void setHistoryPrincipal(Double historyPrincipal) {
		this.historyPrincipal = historyPrincipal;
	}

	public Double getTodayProfit() {
		return todayProfit;
	}

	public void setTodayProfit(Double todayProfit) {
		this.todayProfit = todayProfit;
	}

	public Double getYesterdayPrincipal() {
		return yesterdayPrincipal;
	}

	public void setYesterdayPrincipal(Double yesterdayPrincipal) {
		this.yesterdayPrincipal = yesterdayPrincipal;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public UserAccount(String username, Double availablePrincipal, Double storagePrincipal, Double profit,
			Date signdate, Integer consecutiveDaysNum, Double historyPrincipal, Double todayProfit,
			Double yesterdayPrincipal) {
		super();
		this.username = username;
		this.availablePrincipal = availablePrincipal;
		this.storagePrincipal = storagePrincipal;
		this.profit = profit;
		this.signdate = signdate;
		this.consecutiveDaysNum = consecutiveDaysNum;
		this.historyPrincipal = historyPrincipal;
		this.todayProfit = todayProfit;
		this.yesterdayPrincipal = yesterdayPrincipal;
	}

	@Override
	public String toString() {
		return "UserAccount [username=" + username + ", availablePrincipal=" + availablePrincipal
				+ ", storagePrincipal=" + storagePrincipal + ", profit=" + profit + ", signdate=" + signdate
				+ ", consecutiveDaysNum=" + consecutiveDaysNum + ", historyPrincipal=" + historyPrincipal
				+ ", todayProfit=" + todayProfit + ", yesterdayPrincipal=" + yesterdayPrincipal + "]";
	}

	
	
}
