package PO.user;
// Generated 2017-6-2 16:54:51 by Hibernate Tools 5.2.1.Final

/**
 * UserData generated by hbm2java
 */
public class UserData implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 5129223357358309122L;
	private String username;
	private String password;
	private byte[] avatar;

	public UserData() {
	}

	public UserData(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public UserData(String username, String password, byte[] avatar) {
		this.username = username;
		this.password = password;
		this.avatar = avatar;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public byte[] getAvatar() {
		return this.avatar;
	}

	public void setAvatar(byte[] avatar) {
		this.avatar = avatar;
	}

}
