package PO.user;
// Generated 2017-6-2 16:54:51 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * UserTradeRecord generated by hbm2java
 */
public class UserTradeRecord implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8509774470256229408L;
	private int id;
	private String username;
	private String stockcode;
	private Integer tradenum;
	//0为买入 1为卖出
	private Byte tradetype;
	private Double tradeprice;
	private Date date;

	public UserTradeRecord() {
	}

	public UserTradeRecord(int id) {
		this.id = id;
	}

	public UserTradeRecord(int id,String username, String stockcode, Integer tradenum, Byte tradetype, Double tradeprice,
			Date date) {
		this.id = id;
		this.username = username;
		this.stockcode = stockcode;
		this.tradenum = tradenum;
		this.tradetype = tradetype;
		this.tradeprice = tradeprice;
		this.date = date;
	}

	
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getStockcode() {
		return this.stockcode;
	}

	public void setStockcode(String stockcode) {
		this.stockcode = stockcode;
	}

	public Integer getTradenum() {
		return this.tradenum;
	}

	public void setTradenum(Integer tradenum) {
		this.tradenum = tradenum;
	}

	public Byte getTradetype() {
		return this.tradetype;
	}

	public void setTradetype(Byte tradetype) {
		this.tradetype = tradetype;
	}

	public Double getTradeprice() {
		return this.tradeprice;
	}

	public void setTradeprice(Double tradeprice) {
		this.tradeprice = tradeprice;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
