package PO.user;
// Generated 2017-6-2 16:54:51 by Hibernate Tools 5.2.1.Final

/**
 * UserStockOwned generated by hbm2java
 */
public class UserStockOwned implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6381951620160009231L;
	private UserStockOwnedId id;
	private Integer stocknum;

	public UserStockOwned() {
	}

	public UserStockOwned(UserStockOwnedId id, Integer stocknum) {
		this.id = id;
		this.stocknum = stocknum;
	}

	public UserStockOwnedId getId() {
		return this.id;
	}

	public void setId(UserStockOwnedId id) {
		this.id = id;
	}

	

	public Integer getStocknum() {
		return this.stocknum;
	}

	public void setStocknum(Integer stocknum) {
		this.stocknum = stocknum;
	}

}
