package PO.user;
// Generated 2017-6-2 16:54:51 by Hibernate Tools 5.2.1.Final

/**
 * UserStockOwnedId generated by hbm2java
 */
public class UserStockOwnedId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 537869526003291028L;
	private String username;
	private String stockcode;

	public UserStockOwnedId() {
	}

	public UserStockOwnedId(String username, String stockcode) {
		this.username = username;
		this.stockcode = stockcode;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getStockcode() {
		return this.stockcode;
	}

	public void setStockcode(String stockcode) {
		this.stockcode = stockcode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserStockOwnedId))
			return false;
		UserStockOwnedId castOther = (UserStockOwnedId) other;

		return ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
				&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())))
				&& ((this.getStockcode() == castOther.getStockcode()) || (this.getStockcode() != null
						&& castOther.getStockcode() != null && this.getStockcode().equals(castOther.getStockcode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + (getStockcode() == null ? 0 : this.getStockcode().hashCode());
		return result;
	}

}
